# Features Association Analyzer

In [Chapter -@sec-fam] *Feature Analyzer Module (FAM)* has been developed to identify data features and analyze each feature statistically and visually. So, the logical next step is to analyze the relationship among data features and how they are affecting each other. For example, it would be beneficial to know if a new drug effect is associated with patients age or that a certain gender is interested in a specific study subject, etc. Hence the need to *Features Association Analyzer (FAA)* module to analyze the association between two or more features statistically and visually.

## Introduction

### Function

FAA function is to analyze the association between two or more of data features. The analysis will be determined based on the selected features type and count as follow:

-   Categorical vs Categorical features(@sec-allcat),
-   Categorical vs Numerical features(@sec-catnum),
-   Numerical vs Numerical features (@sec-allnum)

### Input

FAA module is an interactive module that is initialized by data object. After identifying data features, module user will be able to select two or more features to analyze their association. 

### Output

For each association analysis process, FAA generates:

- Interactive and downloadable table with analysis statistical summary (if available) using [periscope2 downloadableTable module](https://aggregate-genius.github.io/periscope2/articles/downloadableTable-module.html)
- Interactive and downloadable visualization plot using [cavansXpress](https://canvasxpress.org/)

Check @fig-3_1 for FAA module objective and IO summary

```{mermaid}
%%| fig-cap: "FAA module objective and IO summary"
%%| fig-width: 5.2
%%| label: fig-3_1

sequenceDiagram
  actor CSA as Client Shiny App
  participant FAAS as FAA Server
  participant FAAU as FAA UI
  
  CSA  ->>  FAAS: Send data
  FAAS ->>  FAAS: Identify features
  FAAS -->> FAAU: Populate features list input
  FAAU ->> CSA: Display multi-select features input
  FAAU ->> CSA: Display analysis trigger button
  CSA  ->>  FAAU: Select features to analyze
  CSA  ->>  FAAU: Click analysis trigger button
  activate FAAS
  FAAU -->> FAAS: Send features list and trigger analysis
  FAAS -->> FAAS: Calculate association statistics
  FAAS -->> FAAU: Populate statistics table
  FAAU ->> CSA: Display statistic downloadable table
  FAAS -->> FAAS: Build association plot
  FAAS -->> FAAU: render CX plot
  FAAU ->> CSA: Display statistic downloadable interactive CX plot
  deactivate FAAS
  
```

*TODO: Refer to app state at this point (GH PR)*

## Categorical vs Categorical features {#sec-allcat}

## Categorical vs Numerical features {#sec-catnum}

## Numerical vs Numerical features {#sec-allnum}

## Exercises

1. **FAM** used both `data.frame` and `tibbles` as a module input. However, `R` has many other data types for storing data (i.e matrix, tables, ...). Please modify **FAM** input to accept additional data type. What needs to be changed? how that will affect other **FAM** functions?

2.  In this chapter, we only discussed and implemented **arithmetic mean**. However, there are other statistical mean functions that can be implemented to enrich your FAM module as [Geometric mean](https://en.wikipedia.org/wiki/Geometric_mean), [Arithmetic--geometric mean](https://en.wikipedia.org/wiki/Arithmetic%E2%80%93geometric_mean) or [Cubic mean](https://en.wikipedia.org/wiki/Cubic_mean). Pick one and implement one of them

3. Define configuration input parameters needed to perform (@sec-cfss) and (@sec-visualization) functions and suggest proper default values.

4.  Using `periscope2` app that is created in chapter 1, implement your own version of **Feature Analyzer** module, then compare your solution against implemented solution in book site.

5.  Integrate `?periscope2::downloadFile` module to your module implementation in order to download all feature statistical summary in one file.



